/*
  sql-bench hand-testing demo -- Oracle. The same online shop as
  demo-mssql.sql, as the schema SHOP (password shop) in FREEPDB1. Run as
  SYSTEM by scripts/demo-up.sh; drops and rebuilds SHOP every time and
  leaves BENCH alone.
*/
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET DEFINE OFF
SET SQLBLANKLINES ON
SET FEEDBACK OFF
SET ECHO OFF

-- An open session (the app, say) would make DROP USER fail.
BEGIN
    FOR s IN (SELECT sid, serial# AS serial FROM v$session WHERE username = 'SHOP') LOOP
        EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial || ''' IMMEDIATE';
    END LOOP;
    EXECUTE IMMEDIATE 'DROP USER shop CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN RAISE; END IF;   -- -1918: no such user
END;
/

CREATE USER shop IDENTIFIED BY shop DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE PROCEDURE,
      CREATE SEQUENCE, CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM TO shop;

CONNECT shop/shop@FREEPDB1

------------------------------------------------------------- sequences
CREATE SEQUENCE order_seq START WITH 120001 CACHE 50;
CREATE SEQUENCE invoice_seq START WITH 950001;
CREATE SEQUENCE ticket_seq START WITH 1 INCREMENT BY 10 MAXVALUE 999999 CYCLE NOCACHE;

------------------------------------------------------------------ tables
CREATE TABLE numbers (n NUMBER(6) CONSTRAINT pk_numbers PRIMARY KEY);

CREATE TABLE departments (
    department_id        NUMBER(4)    CONSTRAINT pk_departments PRIMARY KEY,
    name                 VARCHAR2(60) NOT NULL CONSTRAINT uq_departments_name UNIQUE,
    parent_department_id NUMBER(4)    CONSTRAINT fk_departments_parent REFERENCES departments,
    cost_center          CHAR(6)      NOT NULL
);

CREATE TABLE employees (
    employee_id   NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_employees PRIMARY KEY,
    first_name    NVARCHAR2(50)  NOT NULL,
    last_name     NVARCHAR2(50)  NOT NULL,
    email         VARCHAR2(254)  NOT NULL CONSTRAINT uq_employees_email UNIQUE,
    title         VARCHAR2(80)   NOT NULL,
    department_id NUMBER(4)      NOT NULL CONSTRAINT fk_employees_department REFERENCES departments,
    manager_id    NUMBER(6)      CONSTRAINT fk_employees_manager REFERENCES employees,
    hired_on      DATE           NOT NULL,
    terminated_on DATE,
    salary        NUMBER(10,2)   NOT NULL CONSTRAINT ck_employees_salary CHECK (salary > 0),
    full_name     AS (first_name || ' ' || last_name),
    CONSTRAINT ck_employees_dates CHECK (terminated_on IS NULL OR terminated_on >= hired_on)
);

CREATE TABLE salary_history (
    history_id   NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT pk_salary_history PRIMARY KEY,
    employee_id  NUMBER(6)    NOT NULL CONSTRAINT fk_salary_history_employee REFERENCES employees,
    effective_on DATE         NOT NULL,
    salary       NUMBER(10,2) NOT NULL,
    reason       VARCHAR2(20) NOT NULL CONSTRAINT ck_salary_history_reason
        CHECK (reason IN ('hire', 'merit', 'promotion', 'market', 'correction'))
);

CREATE TABLE categories (
    category_id NUMBER(6)    CONSTRAINT pk_categories PRIMARY KEY,
    parent_id   NUMBER(6)    CONSTRAINT fk_categories_parent REFERENCES categories,
    name        VARCHAR2(80) NOT NULL,
    CONSTRAINT uq_categories_parent_name UNIQUE (parent_id, name)
);

CREATE TABLE suppliers (
    supplier_id   NUMBER(6)      CONSTRAINT pk_suppliers PRIMARY KEY,
    name          NVARCHAR2(120) NOT NULL CONSTRAINT uq_suppliers_name UNIQUE,
    country       CHAR(2)        NOT NULL,
    contact_email VARCHAR2(254)  NOT NULL,
    rating        NUMBER(1)      CONSTRAINT ck_suppliers_rating CHECK (rating BETWEEN 1 AND 5),
    is_active     NUMBER(1)      DEFAULT 1 NOT NULL CONSTRAINT ck_suppliers_active CHECK (is_active IN (0, 1))
);

CREATE TABLE products (
    product_id   NUMBER(8) GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_products PRIMARY KEY,
    sku          VARCHAR2(20)  NOT NULL CONSTRAINT uq_products_sku UNIQUE,
    name         VARCHAR2(120) NOT NULL,
    category_id  NUMBER(6)     NOT NULL CONSTRAINT fk_products_category REFERENCES categories,
    supplier_id  NUMBER(6)     NOT NULL CONSTRAINT fk_products_supplier REFERENCES suppliers,
    list_price   NUMBER(10,2)  NOT NULL CONSTRAINT ck_products_price CHECK (list_price >= 0),
    unit_cost    NUMBER(10,2)  NOT NULL CONSTRAINT ck_products_cost CHECK (unit_cost >= 0),
    weight_kg    NUMBER(7,3),
    discontinued NUMBER(1)     DEFAULT 0 NOT NULL
                               CONSTRAINT ck_products_discontinued CHECK (discontinued IN (0, 1)),
    attributes   CLOB          CONSTRAINT ck_products_attributes_json CHECK (attributes IS JSON),
    created_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    margin_pct   AS (CASE WHEN list_price = 0 THEN NULL
                          ELSE ROUND((list_price - unit_cost) * 100 / list_price, 1) END)
);

CREATE TABLE warehouses (
    warehouse_id NUMBER(4)    CONSTRAINT pk_warehouses PRIMARY KEY,
    code         CHAR(3)      NOT NULL CONSTRAINT uq_warehouses_code UNIQUE,
    city         VARCHAR2(60) NOT NULL,
    country      CHAR(2)      NOT NULL,
    opened_on    DATE         NOT NULL,
    capacity_m3  NUMBER(8)    NOT NULL
);

CREATE TABLE stock (
    warehouse_id  NUMBER(4) NOT NULL CONSTRAINT fk_stock_warehouse REFERENCES warehouses,
    product_id    NUMBER(8) NOT NULL CONSTRAINT fk_stock_product REFERENCES products,
    on_hand       NUMBER(8) DEFAULT 0 NOT NULL CONSTRAINT ck_stock_on_hand CHECK (on_hand >= 0),
    reserved      NUMBER(8) DEFAULT 0 NOT NULL CONSTRAINT ck_stock_reserved CHECK (reserved >= 0),
    reorder_level NUMBER(8) DEFAULT 10 NOT NULL,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    available     AS (on_hand - reserved),
    CONSTRAINT pk_stock PRIMARY KEY (warehouse_id, product_id)
);

CREATE TABLE stock_movements (
    movement_id  NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT pk_stock_movements PRIMARY KEY,
    warehouse_id NUMBER(4)    NOT NULL,
    product_id   NUMBER(8)    NOT NULL,
    qty          NUMBER(8)    NOT NULL CONSTRAINT ck_movements_qty CHECK (qty <> 0),
    reason       VARCHAR2(12) NOT NULL CONSTRAINT ck_movements_reason
        CHECK (reason IN ('receipt', 'sale', 'return', 'adjustment', 'transfer')),
    order_id     NUMBER(10),
    moved_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_movements_stock FOREIGN KEY (warehouse_id, product_id) REFERENCES stock
);

CREATE TABLE customers (
    customer_id      NUMBER(8) GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_customers PRIMARY KEY,
    first_name       NVARCHAR2(50) NOT NULL,
    last_name        NVARCHAR2(50) NOT NULL,
    email            VARCHAR2(254) NOT NULL CONSTRAINT uq_customers_email UNIQUE,
    phone            VARCHAR2(20),
    tier             VARCHAR2(10)  DEFAULT 'bronze' NOT NULL CONSTRAINT ck_customers_tier
        CHECK (tier IN ('bronze', 'silver', 'gold', 'platinum')),
    marketing_opt_in NUMBER(1)     DEFAULT 0 NOT NULL
                                   CONSTRAINT ck_customers_opt_in CHECK (marketing_opt_in IN (0, 1)),
    created_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    notes            NCLOB
);

CREATE TABLE addresses (
    address_id  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_addresses PRIMARY KEY,
    customer_id NUMBER(8)      NOT NULL CONSTRAINT fk_addresses_customer REFERENCES customers ON DELETE CASCADE,
    kind        VARCHAR2(8)    NOT NULL CONSTRAINT ck_addresses_kind CHECK (kind IN ('billing', 'shipping')),
    line1       NVARCHAR2(120) NOT NULL,
    city        NVARCHAR2(60)  NOT NULL,
    region      NVARCHAR2(60),
    postal_code VARCHAR2(12)   NOT NULL,
    country     CHAR(2)        NOT NULL,
    is_default  NUMBER(1)      DEFAULT 0 NOT NULL CONSTRAINT ck_addresses_default CHECK (is_default IN (0, 1))
);

CREATE TABLE promotions (
    promo_code  VARCHAR2(20)  CONSTRAINT pk_promotions PRIMARY KEY,
    description VARCHAR2(200) NOT NULL,
    pct_off     NUMBER(5,2)   NOT NULL CONSTRAINT ck_promotions_pct CHECK (pct_off > 0 AND pct_off <= 90),
    starts_on   DATE          NOT NULL,
    ends_on     DATE          NOT NULL,
    CONSTRAINT ck_promotions_window CHECK (ends_on >= starts_on)
);

CREATE TABLE orders (
    order_id        NUMBER(10)   DEFAULT ON NULL order_seq.NEXTVAL CONSTRAINT pk_orders PRIMARY KEY,
    customer_id     NUMBER(8)    NOT NULL CONSTRAINT fk_orders_customer REFERENCES customers,
    sales_rep_id    NUMBER(6)    CONSTRAINT fk_orders_sales_rep REFERENCES employees,
    ship_address_id NUMBER(10)   CONSTRAINT fk_orders_address REFERENCES addresses,
    warehouse_id    NUMBER(4)    NOT NULL CONSTRAINT fk_orders_warehouse REFERENCES warehouses,
    promo_code      VARCHAR2(20) CONSTRAINT fk_orders_promo REFERENCES promotions,
    status          VARCHAR2(10) DEFAULT 'pending' NOT NULL CONSTRAINT ck_orders_status CHECK (status IN
                        ('pending', 'paid', 'picking', 'shipped', 'delivered', 'cancelled', 'refunded')),
    ordered_at      TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL,
    shipped_at      TIMESTAMP(0),
    subtotal        NUMBER(12,2) DEFAULT 0 NOT NULL,
    discount        NUMBER(12,2) DEFAULT 0 NOT NULL,
    tax             NUMBER(12,2) DEFAULT 0 NOT NULL,
    total           AS (subtotal - discount + tax),
    order_no        AS ('SO-' || TO_CHAR(order_id)),
    CONSTRAINT ck_orders_shipped CHECK (shipped_at IS NULL OR shipped_at >= ordered_at)
);

CREATE TABLE order_lines (
    order_id     NUMBER(10)   NOT NULL CONSTRAINT fk_order_lines_order REFERENCES orders ON DELETE CASCADE,
    line_no      NUMBER(4)    NOT NULL,
    product_id   NUMBER(8)    NOT NULL CONSTRAINT fk_order_lines_product REFERENCES products,
    qty          NUMBER(6)    NOT NULL CONSTRAINT ck_order_lines_qty CHECK (qty > 0),
    unit_price   NUMBER(10,2) NOT NULL,
    discount_pct NUMBER(5,2)  DEFAULT 0 NOT NULL,
    line_total   AS (ROUND(qty * unit_price * (100 - discount_pct) / 100, 2)),
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id, line_no)
);

CREATE TABLE invoices (
    invoice_id  NUMBER(10)   DEFAULT ON NULL invoice_seq.NEXTVAL CONSTRAINT pk_invoices PRIMARY KEY,
    order_id    NUMBER(10)   NOT NULL CONSTRAINT uq_invoices_order UNIQUE
                             CONSTRAINT fk_invoices_order REFERENCES orders,
    issued_on   DATE         NOT NULL,
    due_on      DATE         NOT NULL,
    amount      NUMBER(12,2) NOT NULL,
    paid_amount NUMBER(12,2) DEFAULT 0 NOT NULL,
    currency    CHAR(3)      DEFAULT 'USD' NOT NULL,
    CONSTRAINT ck_invoices_due CHECK (due_on >= issued_on),
    CONSTRAINT ck_invoices_paid CHECK (paid_amount BETWEEN 0 AND amount)
);

CREATE TABLE payments (
    payment_id   NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT pk_payments PRIMARY KEY,
    invoice_id   NUMBER(10)   NOT NULL CONSTRAINT fk_payments_invoice REFERENCES invoices,
    method       VARCHAR2(8)  NOT NULL CONSTRAINT ck_payments_method
        CHECK (method IN ('card', 'paypal', 'wire', 'giftcard')),
    amount       NUMBER(12,2) NOT NULL CONSTRAINT ck_payments_amount CHECK (amount > 0),
    paid_at      TIMESTAMP(3) NOT NULL,
    card_last4   CHAR(4),
    external_ref RAW(16)      DEFAULT SYS_GUID() NOT NULL
);

CREATE TABLE exchange_rates (
    currency     CHAR(3)      NOT NULL,
    rate_date    DATE         NOT NULL,
    usd_per_unit NUMBER(18,8) NOT NULL,
    CONSTRAINT pk_exchange_rates PRIMARY KEY (currency, rate_date)
);

CREATE TABLE change_log (
    change_id   NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT pk_change_log PRIMARY KEY,
    table_name  VARCHAR2(128)  NOT NULL,
    key_value   VARCHAR2(100)  NOT NULL,
    column_name VARCHAR2(128),
    old_value   NVARCHAR2(400),
    new_value   NVARCHAR2(400),
    changed_by  VARCHAR2(128)  DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER') NOT NULL,
    changed_at  TIMESTAMP(3)   DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE app_settings (
    setting_key   VARCHAR2(60)   CONSTRAINT pk_app_settings PRIMARY KEY,
    setting_value NVARCHAR2(400) NOT NULL,
    updated_at    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

-- Quoted, mixed-case names, the way old imports usually look.
CREATE TABLE "Legacy Import 2019" (
    "Row #"          NUMBER,
    "Customer Name"  NVARCHAR2(100),
    "Amount (USD)"   NUMBER(12,2),
    "Imported?"      CHAR(1),
    "Notes/Comments" CLOB
);

COMMENT ON TABLE orders IS 'One row per customer order; totals are kept by sales_pkg.recalculate.';
COMMENT ON COLUMN orders.status IS 'pending -> paid -> picking -> shipped -> delivered, or cancelled/refunded.';
COMMENT ON TABLE stock IS 'On-hand and reserved units per warehouse; stock_movements moves on_hand.';
COMMENT ON TABLE change_log IS 'Written by triggers and by sales_pkg.cancel_order.';

------------------------------------------------------------------- types
CREATE TYPE order_line_t AS OBJECT (product_id NUMBER, qty NUMBER);
/
CREATE TYPE order_line_tab AS TABLE OF order_line_t;
/
CREATE TYPE sales_row_t AS OBJECT (
    bucket VARCHAR2(200), orders NUMBER, units NUMBER, revenue NUMBER, cost NUMBER, gross_margin NUMBER
);
/
CREATE TYPE sales_tab AS TABLE OF sales_row_t;
/
CREATE TYPE org_row_t AS OBJECT (
    employee_id NUMBER, full_name NVARCHAR2(101), title VARCHAR2(80), manager_id NUMBER, depth NUMBER
);
/
CREATE TYPE org_tab AS TABLE OF org_row_t;
/
CREATE TYPE stock_row_t AS OBJECT (
    warehouse CHAR(3), product_id NUMBER, sku VARCHAR2(20), available NUMBER,
    reorder_level NUMBER, order_qty NUMBER
);
/
CREATE TYPE stock_tab AS TABLE OF stock_row_t;
/

------------------------------------------------------------------ views
CREATE OR REPLACE VIEW v_order_summary AS
SELECT o.order_id, o.order_no, o.ordered_at, o.status,
       c.customer_id, c.first_name || ' ' || c.last_name AS customer_name, c.tier,
       e.full_name AS sales_rep, w.code AS warehouse,
       l.line_count, l.units, o.subtotal, o.discount, o.tax, o.total
FROM orders o
JOIN customers c ON c.customer_id = o.customer_id
JOIN warehouses w ON w.warehouse_id = o.warehouse_id
LEFT JOIN employees e ON e.employee_id = o.sales_rep_id
OUTER APPLY (SELECT COUNT(*) AS line_count, SUM(ol.qty) AS units
             FROM order_lines ol WHERE ol.order_id = o.order_id) l;

CREATE OR REPLACE VIEW v_customer_360 AS
WITH stats AS (
    SELECT customer_id, COUNT(*) AS orders, SUM(total) AS lifetime_value,
           MIN(ordered_at) AS first_order_at, MAX(ordered_at) AS last_order_at
    FROM orders
    WHERE status NOT IN ('cancelled', 'refunded')
    GROUP BY customer_id
)
SELECT c.customer_id, c.first_name || ' ' || c.last_name AS name, c.email, c.tier,
       NVL(s.orders, 0) AS orders, NVL(s.lifetime_value, 0) AS lifetime_value,
       s.first_order_at, s.last_order_at,
       TRUNC(SYSDATE) - TRUNC(s.last_order_at) AS days_since_last_order,
       fav.category AS favorite_category, a.city, a.country
FROM customers c
LEFT JOIN stats s ON s.customer_id = c.customer_id
LEFT JOIN addresses a ON a.customer_id = c.customer_id AND a.kind = 'shipping' AND a.is_default = 1
OUTER APPLY (
    SELECT cat.name AS category
    FROM orders o
    JOIN order_lines ol ON ol.order_id = o.order_id
    JOIN products p ON p.product_id = ol.product_id
    JOIN categories cat ON cat.category_id = p.category_id
    WHERE o.customer_id = c.customer_id
    GROUP BY cat.name
    ORDER BY SUM(ol.line_total) DESC, cat.name
    FETCH FIRST 1 ROW ONLY
) fav;

CREATE OR REPLACE VIEW v_category_tree AS
SELECT category_id, parent_id, name, LEVEL - 1 AS depth,
       SUBSTR(SYS_CONNECT_BY_PATH(name, ' > '), 4) AS path,
       CONNECT_BY_ISLEAF AS is_leaf
FROM categories
START WITH parent_id IS NULL
CONNECT BY PRIOR category_id = parent_id;

CREATE OR REPLACE VIEW v_org_chart AS
WITH tree (employee_id, manager_id, full_name, title, department_id, depth, chain) AS (
    SELECT employee_id, manager_id, full_name, title, department_id, 0, CAST(full_name AS NVARCHAR2(1000))
    FROM employees WHERE manager_id IS NULL
    UNION ALL
    SELECT e.employee_id, e.manager_id, e.full_name, e.title, e.department_id, t.depth + 1,
           CAST(t.chain || ' > ' || e.full_name AS NVARCHAR2(1000))
    FROM employees e JOIN tree t ON e.manager_id = t.employee_id
    WHERE e.terminated_on IS NULL
) SEARCH DEPTH FIRST BY full_name SET sort_key
SELECT t.employee_id, LPAD(' ', 4 * t.depth) || t.full_name AS employee, t.title,
       d.name AS department, t.depth, t.chain, t.sort_key
FROM tree t JOIN departments d ON d.department_id = t.department_id;

CREATE OR REPLACE VIEW v_low_stock AS
SELECT w.code AS warehouse, p.product_id, p.sku, p.name AS product,
       s.on_hand, s.reserved, s.available, s.reorder_level,
       sup.name AS supplier, sup.contact_email
FROM stock s
JOIN products p ON p.product_id = s.product_id
JOIN warehouses w ON w.warehouse_id = s.warehouse_id
JOIN suppliers sup ON sup.supplier_id = p.supplier_id
WHERE s.available <= s.reorder_level AND p.discontinued = 0;

CREATE OR REPLACE VIEW v_monthly_revenue AS
WITH m AS (
    SELECT TRUNC(ordered_at, 'MM') AS month_start, COUNT(*) AS orders, SUM(total) AS revenue
    FROM orders
    WHERE status NOT IN ('cancelled', 'refunded')
    GROUP BY TRUNC(ordered_at, 'MM')
)
SELECT month_start, orders, revenue,
       ROUND(revenue / orders, 2) AS avg_order_value,
       SUM(revenue) OVER (PARTITION BY EXTRACT(YEAR FROM month_start) ORDER BY month_start
                          ROWS UNBOUNDED PRECEDING) AS ytd_revenue,
       ROUND(100 * (revenue - LAG(revenue) OVER (ORDER BY month_start))
             / NULLIF(LAG(revenue) OVER (ORDER BY month_start), 0), 2) AS mom_growth_pct
FROM m;

CREATE OR REPLACE VIEW v_product_rankings AS
SELECT cat.name AS category, p.sku, p.name AS product,
       SUM(ol.qty) AS units, SUM(ol.line_total) AS revenue,
       RANK() OVER (PARTITION BY cat.name ORDER BY SUM(ol.line_total) DESC) AS rank_in_category,
       ROUND(100 * RATIO_TO_REPORT(SUM(ol.line_total)) OVER (PARTITION BY cat.name), 2) AS pct_of_category
FROM order_lines ol
JOIN orders o ON o.order_id = ol.order_id
JOIN products p ON p.product_id = ol.product_id
JOIN categories cat ON cat.category_id = p.category_id
WHERE o.status NOT IN ('cancelled', 'refunded')
GROUP BY cat.name, p.sku, p.name;

CREATE OR REPLACE VIEW v_ar_aging AS
SELECT i.invoice_id, o.order_no, c.first_name || ' ' || c.last_name AS customer,
       i.issued_on, i.due_on, i.amount, i.paid_amount, i.amount - i.paid_amount AS outstanding,
       TRUNC(SYSDATE) - i.due_on AS days_overdue,
       CASE WHEN TRUNC(SYSDATE) - i.due_on <= 0 THEN 'current'
            WHEN TRUNC(SYSDATE) - i.due_on <= 30 THEN '1-30'
            WHEN TRUNC(SYSDATE) - i.due_on <= 60 THEN '31-60'
            WHEN TRUNC(SYSDATE) - i.due_on <= 90 THEN '61-90'
            ELSE '90+' END AS bucket
FROM invoices i
JOIN orders o ON o.order_id = i.order_id
JOIN customers c ON c.customer_id = o.customer_id
WHERE i.paid_amount < i.amount;

------------------------------------------------- standalone functions
CREATE OR REPLACE FUNCTION customer_tier (p_lifetime_value IN NUMBER) RETURN VARCHAR2 DETERMINISTIC IS
BEGIN
    RETURN CASE WHEN p_lifetime_value >= 60000 THEN 'platinum'
                WHEN p_lifetime_value >= 25000 THEN 'gold'
                WHEN p_lifetime_value >= 10000 THEN 'silver'
                ELSE 'bronze' END;
END customer_tier;
/

-- Rates exist for weekdays only, so a weekend falls back to Friday.
CREATE OR REPLACE FUNCTION fx_rate (p_currency IN VARCHAR2, p_on IN DATE DEFAULT SYSDATE) RETURN NUMBER IS
    v_rate exchange_rates.usd_per_unit%TYPE;
BEGIN
    IF p_currency = 'USD' THEN
        RETURN 1;
    END IF;
    SELECT MAX(usd_per_unit) KEEP (DENSE_RANK LAST ORDER BY rate_date) INTO v_rate
    FROM exchange_rates
    WHERE currency = p_currency AND rate_date <= TRUNC(p_on);
    IF v_rate IS NULL THEN
        RAISE_APPLICATION_ERROR(-20050, 'No ' || p_currency || ' rate on or before '
                                        || TO_CHAR(p_on, 'YYYY-MM-DD'));
    END IF;
    RETURN v_rate;
END fx_rate;
/

CREATE OR REPLACE FUNCTION to_usd (p_amount IN NUMBER, p_currency IN VARCHAR2, p_on IN DATE DEFAULT SYSDATE)
RETURN NUMBER IS
BEGIN
    RETURN ROUND(p_amount * fx_rate(p_currency, p_on), 2);
END to_usd;
/

CREATE OR REPLACE FUNCTION business_days_between (p_from IN DATE, p_to IN DATE) RETURN NUMBER DETERMINISTIC IS
    v_days NUMBER := 0;
    v_day  DATE := TRUNC(p_from);
BEGIN
    WHILE v_day < TRUNC(p_to) LOOP
        -- An 'IW' week starts on Monday whatever NLS_TERRITORY says: 0-4 are weekdays.
        IF v_day - TRUNC(v_day, 'IW') < 5 THEN
            v_days := v_days + 1;
        END IF;
        v_day := v_day + 1;
    END LOOP;
    RETURN v_days;
END business_days_between;
/

-- For trying cancel on a fetch: select * from slow_rows(30) pipes one row a second.
CREATE OR REPLACE FUNCTION slow_rows (p_rows IN NUMBER DEFAULT 30, p_seconds_each IN NUMBER DEFAULT 1)
RETURN sys.odcinumberlist PIPELINED IS
BEGIN
    FOR i IN 1 .. p_rows LOOP
        DBMS_SESSION.SLEEP(p_seconds_each);
        PIPE ROW (i);
    END LOOP;
    RETURN;
END slow_rows;
/

------------------------------------------------------------- packages
CREATE OR REPLACE PACKAGE sales_pkg AS
    e_no_customer    EXCEPTION;
    e_empty_order    EXCEPTION;
    e_bad_product    EXCEPTION;
    e_out_of_stock   EXCEPTION;
    e_bad_promo      EXCEPTION;
    e_no_order       EXCEPTION;
    e_bad_transition EXCEPTION;
    PRAGMA EXCEPTION_INIT (e_no_customer, -20001);
    PRAGMA EXCEPTION_INIT (e_empty_order, -20002);
    PRAGMA EXCEPTION_INIT (e_bad_product, -20003);
    PRAGMA EXCEPTION_INIT (e_out_of_stock, -20004);
    PRAGMA EXCEPTION_INIT (e_bad_promo, -20005);
    PRAGMA EXCEPTION_INIT (e_no_order, -20010);
    PRAGMA EXCEPTION_INIT (e_bad_transition, -20011);

    FUNCTION place_order (
        p_customer_id  IN customers.customer_id%TYPE,
        p_lines        IN order_line_tab,
        p_warehouse_id IN warehouses.warehouse_id%TYPE DEFAULT 1,
        p_promo_code   IN promotions.promo_code%TYPE DEFAULT NULL,
        p_sales_rep_id IN employees.employee_id%TYPE DEFAULT NULL
    ) RETURN orders.order_id%TYPE;

    FUNCTION quick_order (
        p_customer_id  IN NUMBER,
        p_product_id   IN NUMBER,
        p_qty          IN NUMBER DEFAULT 1,
        p_warehouse_id IN NUMBER DEFAULT 1
    ) RETURN orders.order_id%TYPE;

    -- pending -> paid -> picking -> shipped -> delivered, one step a call.
    PROCEDURE advance_order (p_order_id IN orders.order_id%TYPE);
    PROCEDURE cancel_order (p_order_id IN orders.order_id%TYPE, p_reason IN VARCHAR2);

    -- NULL recalculates every order; the seed uses that once.
    PROCEDURE recalculate (p_order_id IN orders.order_id%TYPE DEFAULT NULL);

    PROCEDURE customer_orders (
        p_customer_id IN  NUMBER,
        p_status      IN  VARCHAR2 DEFAULT NULL,
        p_orders      OUT SYS_REFCURSOR,
        p_by_status   OUT SYS_REFCURSOR
    );

    FUNCTION promo_pct (p_promo_code IN VARCHAR2, p_on IN DATE) RETURN NUMBER;
    FUNCTION tax_rate (p_warehouse_id IN NUMBER) RETURN NUMBER RESULT_CACHE;

    FUNCTION order_total (p_order_id IN NUMBER) RETURN NUMBER;
    FUNCTION order_total (p_order_id IN NUMBER, p_currency IN VARCHAR2) RETURN NUMBER;
END sales_pkg;
/

CREATE OR REPLACE PACKAGE BODY sales_pkg AS

    PROCEDURE release_reservation (p_order_id IN NUMBER, p_warehouse_id IN NUMBER) IS
    BEGIN
        MERGE INTO stock s
        USING (SELECT product_id, SUM(qty) AS qty FROM order_lines
               WHERE order_id = p_order_id GROUP BY product_id) l
        ON (s.product_id = l.product_id AND s.warehouse_id = p_warehouse_id)
        WHEN MATCHED THEN UPDATE SET s.reserved = s.reserved - l.qty, s.updated_at = SYSTIMESTAMP;
    END release_reservation;

    FUNCTION promo_pct (p_promo_code IN VARCHAR2, p_on IN DATE) RETURN NUMBER IS
        v_pct promotions.pct_off%TYPE;
    BEGIN
        IF p_promo_code IS NULL THEN
            RETURN 0;
        END IF;
        SELECT pct_off INTO v_pct FROM promotions
        WHERE promo_code = p_promo_code AND TRUNC(p_on) BETWEEN starts_on AND ends_on;
        RETURN v_pct;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0;
    END promo_pct;

    FUNCTION tax_rate (p_warehouse_id IN NUMBER) RETURN NUMBER RESULT_CACHE IS
        v_country warehouses.country%TYPE;
    BEGIN
        SELECT country INTO v_country FROM warehouses WHERE warehouse_id = p_warehouse_id;
        RETURN CASE v_country WHEN 'US' THEN 0.0825 WHEN 'NL' THEN 0.21 WHEN 'SG' THEN 0.09 ELSE 0 END;
    END tax_rate;

    PROCEDURE recalculate (p_order_id IN orders.order_id%TYPE DEFAULT NULL) IS
    BEGIN
        -- Three passes because each SET sees the row as it was before the UPDATE.
        UPDATE orders o
        SET subtotal = (SELECT NVL(SUM(ol.line_total), 0) FROM order_lines ol WHERE ol.order_id = o.order_id)
        WHERE p_order_id IS NULL OR o.order_id = p_order_id;
        UPDATE orders
        SET discount = ROUND(subtotal * sales_pkg.promo_pct(promo_code, ordered_at) / 100, 2)
        WHERE p_order_id IS NULL OR order_id = p_order_id;
        UPDATE orders
        SET tax = ROUND((subtotal - discount) * sales_pkg.tax_rate(warehouse_id), 2)
        WHERE p_order_id IS NULL OR order_id = p_order_id;
    END recalculate;

    FUNCTION place_order (
        p_customer_id  IN customers.customer_id%TYPE,
        p_lines        IN order_line_tab,
        p_warehouse_id IN warehouses.warehouse_id%TYPE DEFAULT 1,
        p_promo_code   IN promotions.promo_code%TYPE DEFAULT NULL,
        p_sales_rep_id IN employees.employee_id%TYPE DEFAULT NULL
    ) RETURN orders.order_id%TYPE IS
        v_order_id orders.order_id%TYPE;
        v_short    VARCHAR2(4000);
        v_n        PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO v_n FROM customers WHERE customer_id = p_customer_id;
        IF v_n = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'No such customer: ' || p_customer_id);
        END IF;
        IF p_lines IS NULL OR p_lines.COUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'An order needs at least one line.');
        END IF;
        SELECT COUNT(*) INTO v_n
        FROM TABLE(p_lines) l
        LEFT JOIN products p ON p.product_id = l.product_id
        WHERE p.product_id IS NULL OR p.discontinued = 1;
        IF v_n > 0 THEN
            RAISE_APPLICATION_ERROR(-20003, 'An order line names a missing or discontinued product.');
        END IF;
        IF p_promo_code IS NOT NULL AND promo_pct(p_promo_code, SYSDATE) = 0 THEN
            RAISE_APPLICATION_ERROR(-20005, 'Promotion ' || p_promo_code || ' is not valid today.');
        END IF;

        -- Lock the stock rows first, so two orders cannot both take the last unit.
        FOR r IN (SELECT s.product_id FROM stock s
                  WHERE s.warehouse_id = p_warehouse_id
                    AND s.product_id IN (SELECT l.product_id FROM TABLE(p_lines) l)
                  FOR UPDATE) LOOP
            NULL;
        END LOOP;

        SELECT LISTAGG(p.sku || ' (' || NVL(s.available, 0) || ' left, ' || l.qty || ' wanted)', ', ')
                   WITHIN GROUP (ORDER BY p.sku)
        INTO v_short
        FROM TABLE(p_lines) l
        JOIN products p ON p.product_id = l.product_id
        LEFT JOIN stock s ON s.product_id = l.product_id AND s.warehouse_id = p_warehouse_id
        WHERE NVL(s.available, 0) < l.qty;
        IF v_short IS NOT NULL THEN
            RAISE_APPLICATION_ERROR(-20004, 'Not enough stock: ' || v_short);
        END IF;

        INSERT INTO orders (customer_id, sales_rep_id, ship_address_id, warehouse_id, promo_code)
        VALUES (p_customer_id, p_sales_rep_id,
                (SELECT MIN(address_id) KEEP (DENSE_RANK FIRST ORDER BY is_default DESC)
                 FROM addresses WHERE customer_id = p_customer_id AND kind = 'shipping'),
                p_warehouse_id, p_promo_code)
        RETURNING order_id INTO v_order_id;

        INSERT INTO order_lines (order_id, line_no, product_id, qty, unit_price)
        SELECT v_order_id, ROW_NUMBER() OVER (ORDER BY l.product_id), l.product_id, l.qty, p.list_price
        FROM TABLE(p_lines) l JOIN products p ON p.product_id = l.product_id;

        MERGE INTO stock s
        USING (SELECT product_id, SUM(qty) AS qty FROM TABLE(p_lines) GROUP BY product_id) l
        ON (s.product_id = l.product_id AND s.warehouse_id = p_warehouse_id)
        WHEN MATCHED THEN UPDATE SET s.reserved = s.reserved + l.qty, s.updated_at = SYSTIMESTAMP;

        recalculate(v_order_id);
        COMMIT;
        RETURN v_order_id;
    END place_order;

    FUNCTION quick_order (
        p_customer_id  IN NUMBER,
        p_product_id   IN NUMBER,
        p_qty          IN NUMBER DEFAULT 1,
        p_warehouse_id IN NUMBER DEFAULT 1
    ) RETURN orders.order_id%TYPE IS
    BEGIN
        RETURN place_order(p_customer_id, order_line_tab(order_line_t(p_product_id, p_qty)), p_warehouse_id);
    END quick_order;

    PROCEDURE advance_order (p_order_id IN orders.order_id%TYPE) IS
        v_status     orders.status%TYPE;
        v_warehouse  orders.warehouse_id%TYPE;
        v_total      NUMBER;
        v_invoice_id invoices.invoice_id%TYPE;
    BEGIN
        SELECT status, warehouse_id, total INTO v_status, v_warehouse, v_total
        FROM orders WHERE order_id = p_order_id FOR UPDATE;

        CASE v_status
            WHEN 'pending' THEN
                -- Payment is taken up front: invoice the order and settle it by card.
                INSERT INTO invoices (order_id, issued_on, due_on, amount, paid_amount)
                VALUES (p_order_id, TRUNC(SYSDATE), TRUNC(SYSDATE) + 30, v_total, v_total)
                RETURNING invoice_id INTO v_invoice_id;
                INSERT INTO payments (invoice_id, method, amount, paid_at, card_last4)
                VALUES (v_invoice_id, 'card', v_total, SYSTIMESTAMP, '4242');
                UPDATE orders SET status = 'paid' WHERE order_id = p_order_id;
            WHEN 'paid' THEN
                UPDATE orders SET status = 'picking' WHERE order_id = p_order_id;
            WHEN 'picking' THEN
                -- The movement trigger takes the units off on_hand; the reservation goes with them.
                INSERT INTO stock_movements (warehouse_id, product_id, qty, reason, order_id)
                SELECT v_warehouse, product_id, -SUM(qty), 'sale', p_order_id
                FROM order_lines WHERE order_id = p_order_id GROUP BY product_id;
                release_reservation(p_order_id, v_warehouse);
                UPDATE orders SET status = 'shipped', shipped_at = SYSTIMESTAMP WHERE order_id = p_order_id;
            WHEN 'shipped' THEN
                UPDATE orders SET status = 'delivered' WHERE order_id = p_order_id;
            ELSE
                RAISE_APPLICATION_ERROR(-20011, 'Order ' || p_order_id || ' is ' || v_status
                                                || '; nothing comes after that.');
        END CASE;
        COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20010, 'No such order: ' || p_order_id);
    END advance_order;

    PROCEDURE cancel_order (p_order_id IN orders.order_id%TYPE, p_reason IN VARCHAR2) IS
        v_status    orders.status%TYPE;
        v_warehouse orders.warehouse_id%TYPE;
    BEGIN
        SELECT status, warehouse_id INTO v_status, v_warehouse
        FROM orders WHERE order_id = p_order_id FOR UPDATE;
        IF v_status NOT IN ('pending', 'paid', 'picking') THEN
            RAISE_APPLICATION_ERROR(-20011, 'Order ' || p_order_id || ' is ' || v_status
                                            || ' and cannot be cancelled.');
        END IF;
        release_reservation(p_order_id, v_warehouse);
        -- Money already taken goes back, which makes it a refund, not a cancellation.
        UPDATE orders SET status = CASE v_status WHEN 'pending' THEN 'cancelled' ELSE 'refunded' END
        WHERE order_id = p_order_id;
        INSERT INTO change_log (table_name, key_value, column_name, new_value)
        VALUES ('ORDERS', TO_CHAR(p_order_id), 'CANCEL_REASON', SUBSTR(p_reason, 1, 400));
        COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20010, 'No such order: ' || p_order_id);
    END cancel_order;

    PROCEDURE customer_orders (
        p_customer_id IN  NUMBER,
        p_status      IN  VARCHAR2 DEFAULT NULL,
        p_orders      OUT SYS_REFCURSOR,
        p_by_status   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_orders FOR
            SELECT order_id, order_no, ordered_at, status, line_count, units, total, sales_rep, warehouse
            FROM v_order_summary
            WHERE customer_id = p_customer_id AND (p_status IS NULL OR status = p_status)
            ORDER BY ordered_at DESC;
        OPEN p_by_status FOR
            SELECT status, COUNT(*) AS orders, SUM(total) AS total
            FROM orders WHERE customer_id = p_customer_id
            GROUP BY status ORDER BY orders DESC;
    END customer_orders;

    FUNCTION order_total (p_order_id IN NUMBER) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT total INTO v_total FROM orders WHERE order_id = p_order_id;
        RETURN v_total;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END order_total;

    FUNCTION order_total (p_order_id IN NUMBER, p_currency IN VARCHAR2) RETURN NUMBER IS
    BEGIN
        RETURN ROUND(order_total(p_order_id) / fx_rate(p_currency, SYSDATE), 2);
    END order_total;
END sales_pkg;
/

CREATE OR REPLACE PACKAGE hr_pkg AS
    -- Read by trg_employees_salary, so a raise records why it happened.
    g_raise_reason salary_history.reason%TYPE;

    PROCEDURE give_raise (p_employee_id IN NUMBER, p_pct IN NUMBER, p_reason IN VARCHAR2 DEFAULT 'merit');
    FUNCTION reports_to (p_manager_id IN NUMBER) RETURN org_tab PIPELINED;
    FUNCTION headcount (p_department_id IN NUMBER) RETURN NUMBER;
END hr_pkg;
/

CREATE OR REPLACE PACKAGE BODY hr_pkg AS
    PROCEDURE give_raise (p_employee_id IN NUMBER, p_pct IN NUMBER, p_reason IN VARCHAR2 DEFAULT 'merit') IS
    BEGIN
        IF p_pct <= 0 OR p_pct > 25 THEN
            RAISE_APPLICATION_ERROR(-20030, 'A raise is more than 0 and at most 25 percent.');
        END IF;
        IF p_reason NOT IN ('merit', 'promotion', 'market', 'correction') THEN
            RAISE_APPLICATION_ERROR(-20031, 'reason is merit, promotion, market or correction.');
        END IF;
        g_raise_reason := p_reason;
        UPDATE employees SET salary = ROUND(salary * (1 + p_pct / 100), 2)
        WHERE employee_id = p_employee_id AND terminated_on IS NULL;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20032, 'No such active employee: ' || p_employee_id);
        END IF;
        g_raise_reason := NULL;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            g_raise_reason := NULL;
            RAISE;
    END give_raise;

    FUNCTION reports_to (p_manager_id IN NUMBER) RETURN org_tab PIPELINED IS
    BEGIN
        FOR r IN (SELECT employee_id, full_name, title, manager_id, LEVEL - 1 AS depth
                  FROM employees
                  START WITH employee_id = p_manager_id
                  CONNECT BY PRIOR employee_id = manager_id AND terminated_on IS NULL
                  ORDER SIBLINGS BY last_name) LOOP
            PIPE ROW (org_row_t(r.employee_id, r.full_name, r.title, r.manager_id, r.depth));
        END LOOP;
        RETURN;
    END reports_to;

    FUNCTION headcount (p_department_id IN NUMBER) RETURN NUMBER IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM employees
        WHERE terminated_on IS NULL
          AND department_id IN (SELECT department_id FROM departments
                                START WITH department_id = p_department_id
                                CONNECT BY PRIOR department_id = parent_department_id);
        RETURN v_count;
    END headcount;
END hr_pkg;
/

CREATE OR REPLACE PACKAGE inventory_pkg AS
    c_default_multiplier CONSTANT PLS_INTEGER := 2;

    FUNCTION availability (p_product_id IN NUMBER) RETURN stock_tab PIPELINED;
    -- What restock would order, without ordering it.
    FUNCTION restock_plan (p_warehouse_id IN NUMBER DEFAULT NULL) RETURN stock_tab PIPELINED;
    PROCEDURE restock (p_warehouse_id IN NUMBER DEFAULT NULL);
END inventory_pkg;
/

CREATE OR REPLACE PACKAGE BODY inventory_pkg AS
    FUNCTION multiplier RETURN PLS_INTEGER IS
        v_value NUMBER;
    BEGIN
        SELECT TO_NUMBER(setting_value DEFAULT NULL ON CONVERSION ERROR) INTO v_value
        FROM app_settings WHERE setting_key = 'inventory.restock_multiplier';
        RETURN NVL(v_value, c_default_multiplier);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN c_default_multiplier;
    END multiplier;

    FUNCTION availability (p_product_id IN NUMBER) RETURN stock_tab PIPELINED IS
    BEGIN
        FOR r IN (SELECT w.code, s.product_id, p.sku, s.available, s.reorder_level
                  FROM stock s
                  JOIN warehouses w ON w.warehouse_id = s.warehouse_id
                  JOIN products p ON p.product_id = s.product_id
                  WHERE s.product_id = p_product_id
                  ORDER BY w.code) LOOP
            PIPE ROW (stock_row_t(r.code, r.product_id, r.sku, r.available, r.reorder_level, NULL));
        END LOOP;
        RETURN;
    END availability;

    FUNCTION restock_plan (p_warehouse_id IN NUMBER DEFAULT NULL) RETURN stock_tab PIPELINED IS
        v_multiplier PLS_INTEGER := multiplier;
    BEGIN
        FOR r IN (SELECT w.code, s.product_id, p.sku, s.available, s.reorder_level
                  FROM stock s
                  JOIN warehouses w ON w.warehouse_id = s.warehouse_id
                  JOIN products p ON p.product_id = s.product_id
                  WHERE s.available <= s.reorder_level AND p.discontinued = 0
                    AND (p_warehouse_id IS NULL OR s.warehouse_id = p_warehouse_id)
                  ORDER BY w.code, p.sku) LOOP
            PIPE ROW (stock_row_t(r.code, r.product_id, r.sku, r.available, r.reorder_level,
                                  r.reorder_level * v_multiplier - r.available));
        END LOOP;
        RETURN;
    END restock_plan;

    PROCEDURE restock (p_warehouse_id IN NUMBER DEFAULT NULL) IS
    BEGIN
        INSERT INTO stock_movements (warehouse_id, product_id, qty, reason)
        SELECT w.warehouse_id, t.product_id, t.order_qty, 'receipt'
        FROM TABLE(inventory_pkg.restock_plan(p_warehouse_id)) t
        JOIN warehouses w ON w.code = t.warehouse;
        COMMIT;
    END restock;
END inventory_pkg;
/

CREATE OR REPLACE PACKAGE report_pkg AS
    FUNCTION sales_report (
        p_from     IN DATE DEFAULT ADD_MONTHS(TRUNC(SYSDATE), -12),
        p_to       IN DATE DEFAULT TRUNC(SYSDATE),
        p_group_by IN VARCHAR2 DEFAULT 'month'
    ) RETURN sales_tab PIPELINED;
    PROCEDURE refresh_daily_sales;
END report_pkg;
/

CREATE OR REPLACE PACKAGE BODY report_pkg AS
    FUNCTION sales_report (
        p_from     IN DATE DEFAULT ADD_MONTHS(TRUNC(SYSDATE), -12),
        p_to       IN DATE DEFAULT TRUNC(SYSDATE),
        p_group_by IN VARCHAR2 DEFAULT 'month'
    ) RETURN sales_tab PIPELINED IS
        v_bucket VARCHAR2(200);
        v_cur    SYS_REFCURSOR;
        v_row    sales_row_t := sales_row_t(NULL, NULL, NULL, NULL, NULL, NULL);
    BEGIN
        v_bucket := CASE LOWER(p_group_by)
            WHEN 'day' THEN 'TO_CHAR(o.ordered_at, ''YYYY-MM-DD'')'
            WHEN 'week' THEN 'TO_CHAR(TRUNC(o.ordered_at, ''IW''), ''YYYY-MM-DD'')'
            WHEN 'month' THEN 'TO_CHAR(o.ordered_at, ''YYYY-MM'')'
            WHEN 'category' THEN 'cat.name'
            WHEN 'warehouse' THEN 'w.code'
            WHEN 'rep' THEN 'NVL(TO_CHAR(e.full_name), ''(house)'')'
        END;
        IF v_bucket IS NULL THEN
            RAISE_APPLICATION_ERROR(-20020, 'group_by is day, week, month, category, warehouse or rep.');
        END IF;

        OPEN v_cur FOR
            'SELECT ' || v_bucket || ', COUNT(DISTINCT o.order_id), SUM(ol.qty),
                    SUM(ol.line_total), SUM(ol.qty * p.unit_cost)
             FROM orders o
             JOIN order_lines ol ON ol.order_id = o.order_id
             JOIN products p ON p.product_id = ol.product_id
             JOIN categories cat ON cat.category_id = p.category_id
             JOIN warehouses w ON w.warehouse_id = o.warehouse_id
             LEFT JOIN employees e ON e.employee_id = o.sales_rep_id
             WHERE o.ordered_at >= :f AND o.ordered_at < :t + 1
               AND o.status NOT IN (''cancelled'', ''refunded'')
             GROUP BY ' || v_bucket || '
             ORDER BY ' || CASE WHEN LOWER(p_group_by) IN ('day', 'week', 'month') THEN '1' ELSE '4 DESC' END
            USING p_from, p_to;
        LOOP
            FETCH v_cur INTO v_row.bucket, v_row.orders, v_row.units, v_row.revenue, v_row.cost;
            EXIT WHEN v_cur%NOTFOUND;
            v_row.gross_margin := v_row.revenue - v_row.cost;
            PIPE ROW (v_row);
        END LOOP;
        CLOSE v_cur;
        RETURN;
    END sales_report;

    PROCEDURE refresh_daily_sales IS
    BEGIN
        DBMS_MVIEW.REFRESH('MV_DAILY_SALES', 'C');
    END refresh_daily_sales;
END report_pkg;
/

---------------------------------------------------- standalone procedures
CREATE OR REPLACE PROCEDURE refresh_customer_tiers IS
BEGIN
    MERGE INTO customers c
    USING (SELECT c2.customer_id, customer_tier(NVL(v.lifetime_value, 0)) AS tier
           FROM customers c2
           LEFT JOIN (SELECT customer_id, SUM(total) AS lifetime_value
                      FROM orders WHERE status NOT IN ('cancelled', 'refunded')
                      GROUP BY customer_id) v ON v.customer_id = c2.customer_id) t
    ON (c.customer_id = t.customer_id)
    WHEN MATCHED THEN UPDATE SET c.tier = t.tier WHERE c.tier <> t.tier;
    COMMIT;
END refresh_customer_tiers;
/

CREATE OR REPLACE PROCEDURE purge_change_log (p_older_than_days IN NUMBER DEFAULT 90,
                                              p_batch_size IN NUMBER DEFAULT 500) IS
    v_cutoff TIMESTAMP := SYSTIMESTAMP - NUMTODSINTERVAL(p_older_than_days, 'DAY');
BEGIN
    LOOP
        DELETE FROM change_log WHERE changed_at < v_cutoff AND ROWNUM <= p_batch_size;
        EXIT WHEN SQL%ROWCOUNT = 0;
        COMMIT;
    END LOOP;
    COMMIT;
END purge_change_log;
/

-- For trying cancel: begin slow_query(30); end;
CREATE OR REPLACE PROCEDURE slow_query (p_seconds IN NUMBER DEFAULT 10) IS
BEGIN
    DBMS_SESSION.SLEEP(p_seconds);
END slow_query;
/

------------------------------------------------------------------- data
INSERT INTO numbers (n) SELECT LEVEL FROM dual CONNECT BY LEVEL <= 100000;

INSERT INTO departments (department_id, name, parent_department_id, cost_center) VALUES
    (1, 'Executive', NULL, 'CC1000'),
    (2, 'Sales', 1, 'CC2000'),
    (3, 'Sales EMEA', 2, 'CC2100'),
    (4, 'Sales Americas', 2, 'CC2200'),
    (5, 'Operations', 1, 'CC3000'),
    (6, 'Warehouse', 5, 'CC3100'),
    (7, 'Finance', 1, 'CC4000'),
    (8, 'Engineering', 1, 'CC5000'),
    (9, 'Customer Support', 5, 'CC3200'),
    (10, 'Marketing', 1, 'CC6000');

-- Each department head's employee_id is the department_id, so the
-- generated staff below can take their manager straight from it.
INSERT INTO employees (employee_id, first_name, last_name, email, title, department_id, manager_id, hired_on, salary) VALUES
    (1, N'Margaret', N'Okonkwo', 'margaret.okonkwo@shop.test', 'Chief Executive Officer', 1, NULL, DATE '2016-02-01', 310000),
    (2, N'Daniel', N'Hernández', 'daniel.hernandez@shop.test', 'VP Sales', 2, 1, DATE '2017-05-15', 225000),
    (3, N'Sophie', N'Laurent', 'sophie.laurent@shop.test', 'Director, Sales EMEA', 3, 2, DATE '2018-09-03', 178000),
    (4, N'Marcus', N'Webb', 'marcus.webb@shop.test', 'Director, Sales Americas', 4, 2, DATE '2018-11-12', 181000),
    (5, N'Yuki', N'Watanabe', 'yuki.watanabe@shop.test', 'Chief Operating Officer', 5, 1, DATE '2016-08-22', 255000),
    (6, N'Tomás', N'Oliveira', 'tomas.oliveira@shop.test', 'Warehouse Manager', 6, 5, DATE '2019-03-04', 98000),
    (7, N'Hannah', N'Schmidt', 'hannah.schmidt@shop.test', 'Chief Financial Officer', 7, 1, DATE '2017-01-09', 240000),
    (8, N'Ravi', N'Krishnan', 'ravi.krishnan@shop.test', 'Chief Technology Officer', 8, 1, DATE '2017-10-30', 262000),
    (9, N'Aoife', N'Byrne', 'aoife.byrne@shop.test', 'Support Lead', 9, 5, DATE '2020-06-01', 89000),
    (10, N'Lena', N'Johansson', 'lena.johansson@shop.test', 'Chief Marketing Officer', 10, 1, DATE '2018-04-16', 215000);

INSERT INTO employees (employee_id, first_name, last_name, email, title, department_id, manager_id,
                       hired_on, terminated_on, salary)
SELECT 10 + n,
       REGEXP_SUBSTR(N'Olivia,Liam,Emma,Noah,Sofía,Mateo,Chloé,Lukas,Aiko,Wei,Priya,Arjun,Fatima,Omar,Ingrid,Björn,Zoë,Dmitri,Grace,Kwame',
                     '[^,]+', 1, MOD(n * 7, 20) + 1),
       REGEXP_SUBSTR(N'Smith,García,Müller,Rossi,Tanaka,Chen,Patel,Okafor,Johansson,Kowalski,Nguyen,O''Brien,Dubois,Silva,Kim,Haddad,Novák,Andersen,Ivanova,Moreau',
                     '[^,]+', 1, MOD(n * 3, 20) + 1),
       'emp' || (10 + n) || '@shop.test',
       REGEXP_SUBSTR('Account Executive,Account Executive,Account Executive,Operations Analyst,Warehouse Associate,Accountant,Software Engineer,Support Specialist,Marketing Specialist',
                     '[^,]+', 1, dept - 1),
       dept, dept, hired_on,
       CASE WHEN MOD(n, 17) = 0 AND hired_on < DATE '2025-06-01' THEN hired_on + 300 END,
       52000 + MOD(n * 1373, 60000)
FROM (SELECT n, MOD(n, 9) + 2 AS dept, DATE '2026-08-01' - MOD(n * 37, 2500) AS hired_on
      FROM numbers WHERE n <= 50);

ALTER TABLE employees MODIFY employee_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);

INSERT INTO salary_history (employee_id, effective_on, salary, reason)
SELECT employee_id, hired_on,
       CASE WHEN ADD_MONTHS(hired_on, 12) <= DATE '2026-09-01' THEN ROUND(salary * 0.88, 2) ELSE salary END,
       'hire'
FROM employees
UNION ALL
SELECT employee_id, ADD_MONTHS(hired_on, 12), salary,
       CASE WHEN MOD(employee_id, 4) = 0 THEN 'promotion' ELSE 'merit' END
FROM employees
WHERE ADD_MONTHS(hired_on, 12) <= DATE '2026-09-01';

INSERT INTO categories (category_id, parent_id, name) VALUES
    (1, NULL, 'Electronics'), (2, 1, 'Audio'), (3, 2, 'Headphones'), (4, 2, 'Speakers'),
    (5, 1, 'Computers'), (6, 5, 'Laptops'), (7, 5, 'Monitors'), (8, 5, 'Accessories'),
    (9, NULL, 'Home & Kitchen'), (10, 9, 'Cookware'), (11, 9, 'Small Appliances'), (12, 11, 'Coffee'),
    (13, NULL, 'Outdoors'), (14, 13, 'Camping'), (15, 13, 'Cycling'),
    (16, NULL, 'Books'), (17, 16, 'Fiction'), (18, 16, 'Technical');

INSERT INTO suppliers (supplier_id, name, country, contact_email, rating, is_active) VALUES
    (1, N'Northwind Audio', 'US', 'orders@northwind-audio.test', 5, 1),
    (2, N'Kōbe Electronics', 'JP', 'sales@kobe-elec.test', 4, 1),
    (3, N'Rhein Computing GmbH', 'DE', 'vertrieb@rhein-computing.test', 4, 1),
    (4, N'Pacific Displays', 'SG', 'b2b@pacific-displays.test', 3, 1),
    (5, N'Cable & Co', 'GB', 'hello@cableandco.test', 4, 1),
    (6, N'Casa Cucina', 'IT', 'ordini@casacucina.test', 5, 1),
    (7, N'Bean There Coffee Gear', 'NL', 'wholesale@beanthere.test', 4, 1),
    (8, N'Trailhead Outfitters', 'CA', 'supply@trailhead.test', 3, 1),
    (9, N'Vélo Parts', 'FR', 'commandes@veloparts.test', 4, 1),
    (10, N'Paperback Press', 'US', 'trade@paperback.test', 5, 1),
    (11, N'Stackwise Books', 'US', 'orders@stackwise.test', 4, 1),
    (12, N'Defunct Imports Ltd', 'GB', 'nobody@defunct.test', 1, 0);

INSERT INTO products (product_id, sku, name, category_id, supplier_id, list_price, unit_cost,
                      weight_kg, discontinued, attributes, created_at)
SELECT n,
       REGEXP_SUBSTR('AUD,AUD,CMP,CMP,CMP,HOM,HOM,OUT,OUT,BKS,BKS', '[^,]+', 1, k) || '-' || TO_CHAR(n, 'FM0000'),
       REGEXP_SUBSTR('Pro,Lite,Max,Mini,Ultra,Classic,Eco,Smart,Travel,Studio', '[^,]+', 1, MOD(n, 10) + 1) || ' '
           || REGEXP_SUBSTR('Headphones,Speaker,Laptop,Monitor,USB-C Hub,Skillet,Espresso Machine,Tent,Bike Light,Novel,Programming Guide',
                            '[^,]+', 1, k) || ' ' || n,
       TO_NUMBER(REGEXP_SUBSTR('3,4,6,7,8,10,12,14,15,17,18', '[^,]+', 1, k)),
       MOD(n, 12) + 1,
       list_price,
       ROUND(list_price * (0.5 + MOD(n, 5) * 0.05), 2),
       CASE WHEN k < 10 THEN 0.2 + MOD(n, 40) * 0.15 END,
       CASE WHEN MOD(n, 23) = 0 THEN 1 ELSE 0 END,
       CASE WHEN MOD(n, 3) = 0 THEN '{"color":"' || REGEXP_SUBSTR('black,white,silver,red,blue', '[^,]+', 1, MOD(n, 5) + 1)
                                    || '","warranty_months":' || 12 * (MOD(n, 4) + 1) || '}' END,
       TIMESTAMP '2026-06-01 10:00:00' - NUMTODSINTERVAL(n * 3, 'DAY')
FROM (SELECT n, k,
             ROUND(TO_NUMBER(REGEXP_SUBSTR('149,89,1299,329,49,59,449,219,35,18,54', '[^,]+', 1, k))
                   * (0.8 + MOD(n, 7) * 0.1) - 0.01, 2) AS list_price
      FROM (SELECT n, MOD(n, 11) + 1 AS k FROM numbers WHERE n <= 300));

ALTER TABLE products MODIFY product_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);

INSERT INTO warehouses (warehouse_id, code, city, country, opened_on, capacity_m3) VALUES
    (1, 'DAL', 'Dallas', 'US', DATE '2016-03-01', 42000),
    (2, 'RTM', 'Rotterdam', 'NL', DATE '2019-09-15', 30000),
    (3, 'SIN', 'Singapore', 'SG', DATE '2021-05-10', 18000),
    (4, 'CHI', 'Chicago', 'US', DATE '2023-02-20', 25000);

INSERT INTO stock (warehouse_id, product_id, on_hand, reorder_level)
SELECT w.warehouse_id, p.product_id,
       MOD(p.product_id * 37 + w.warehouse_id * 11, 120),
       10 + MOD(p.product_id, 4) * 10
FROM warehouses w CROSS JOIN products p;

INSERT INTO promotions (promo_code, description, pct_off, starts_on, ends_on) VALUES
    ('WELCOME10', '10% off for new customers', 10, DATE '2023-01-01', DATE '2027-12-31'),
    ('LOYAL5', '5% loyalty discount', 5, DATE '2024-01-01', DATE '2026-12-31'),
    ('SPRING24', 'Spring sale 2024', 15, DATE '2024-03-01', DATE '2024-05-31'),
    ('BF2024', 'Black Friday 2024', 25, DATE '2024-11-25', DATE '2024-12-02'),
    ('SUMMER25', 'Summer sale 2025', 12, DATE '2025-06-01', DATE '2025-08-31'),
    ('BF2025', 'Black Friday 2025', 30, DATE '2025-11-24', DATE '2025-12-01');

INSERT INTO customers (customer_id, first_name, last_name, email, phone, marketing_opt_in, created_at, notes)
SELECT n,
       REGEXP_SUBSTR(N'Olivia,Liam,Emma,Noah,Sofía,Mateo,Chloé,Lukas,Aiko,Wei,Priya,Arjun,Fatima,Omar,Ingrid,Björn,Zoë,Dmitri,Grace,Kwame',
                     '[^,]+', 1, MOD(n, 20) + 1),
       REGEXP_SUBSTR(N'Smith,García,Müller,Rossi,Tanaka,Chen,Patel,Okafor,Johansson,Kowalski,Nguyen,O''Brien,Dubois,Silva,Kim,Haddad,Novák,Andersen,Ivanova,Moreau',
                     '[^,]+', 1, MOD(TRUNC(n / 20), 20) + 1),
       'customer' || n || '@' || REGEXP_SUBSTR('example.com,mail.test,shop.test,inbox.test', '[^,]+', 1, MOD(n, 4) + 1),
       CASE WHEN MOD(n, 6) <> 0 THEN '+1-555-' || TO_CHAR(MOD(n * 17, 10000), 'FM0000') END,
       CASE WHEN MOD(n, 3) = 0 THEN 1 ELSE 0 END,
       TIMESTAMP '2023-01-01 09:00:00' + NUMTODSINTERVAL(n * 4, 'HOUR'),
       CASE WHEN MOD(n, 50) = 0 THEN TO_NCLOB(N'VIP — call before shipping.' || CHR(10)
                                              || N'Prefers email; allergic to spam 🙂') END
FROM numbers WHERE n <= 2000;

ALTER TABLE customers MODIFY customer_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);

INSERT INTO addresses (customer_id, kind, line1, city, region, postal_code, country, is_default)
SELECT c.n, k.kind,
       (MOD(c.n * 13, 900) + 100 + k.bump) || ' '
           || REGEXP_SUBSTR(N'Maple St,Oak Ave,Harbour Rd,Königstraße,Rue de Rivoli,Canal St,Sakura-dori,Orchard Rd',
                            '[^,]+', 1, MOD(c.n, 8) + 1),
       REGEXP_SUBSTR(N'Austin,Toronto,London,Berlin,Lyon,Utrecht,Osaka,Singapore,Melbourne,São Paulo',
                     '[^,]+', 1, MOD(c.n, 10) + 1),
       NULLIF(REGEXP_SUBSTR('TX,ON,-,BE,-,UT,-,-,VIC,SP', '[^,]+', 1, MOD(c.n, 10) + 1), '-'),
       TO_CHAR(MOD(c.n * 7717, 99999), 'FM00000'),
       REGEXP_SUBSTR('US,CA,GB,DE,FR,NL,JP,SG,AU,BR', '[^,]+', 1, MOD(c.n, 10) + 1),
       k.is_default
FROM numbers c
CROSS JOIN (VALUES ('billing', 0, 1), ('shipping', 0, 1), ('shipping', 7, 0)) k (kind, bump, is_default)
WHERE c.n <= 2000 AND (k.is_default = 1 OR MOD(c.n, 5) = 0);

-- 20,000 orders, one every 71 minutes from 2024-01-01; a third of them go
-- to the first 200 customers, so tiers come out uneven.
INSERT INTO orders (order_id, customer_id, sales_rep_id, ship_address_id, warehouse_id, promo_code,
                    status, ordered_at, shipped_at)
WITH reps AS (
    SELECT employee_id, ROW_NUMBER() OVER (ORDER BY employee_id) - 1 AS rn, COUNT(*) OVER () AS cnt
    FROM employees WHERE department_id IN (2, 3, 4) AND terminated_on IS NULL
), x AS (
    SELECT n,
           CASE WHEN MOD(n, 3) = 0 THEN MOD(n * 7919, 200) + 1 ELSE MOD(n * 7919, 2000) + 1 END AS customer_id,
           MOD(n, 4) + 1 AS warehouse_id,
           CAST(TIMESTAMP '2024-01-01 08:00:00' + NUMTODSINTERVAL(n * 71, 'MINUTE') AS TIMESTAMP(0)) AS ordered_at,
           CASE WHEN n > 19950 THEN 'pending' WHEN n > 19900 THEN 'paid' WHEN n > 19850 THEN 'picking'
                WHEN n > 19700 THEN 'shipped' WHEN MOD(n, 97) = 0 THEN 'refunded'
                WHEN MOD(n, 29) = 0 THEN 'cancelled' ELSE 'delivered' END AS status
    FROM numbers WHERE n <= 20000
)
SELECT 100000 + x.n, x.customer_id, r.employee_id, a.address_id, x.warehouse_id,
       CASE WHEN x.ordered_at BETWEEN DATE '2024-11-25' AND DATE '2024-12-03' AND MOD(x.n, 2) = 0 THEN 'BF2024'
            WHEN x.ordered_at BETWEEN DATE '2025-11-24' AND DATE '2025-12-02' AND MOD(x.n, 2) = 0 THEN 'BF2025'
            WHEN x.ordered_at BETWEEN DATE '2024-03-01' AND DATE '2024-06-01' AND MOD(x.n, 5) = 0 THEN 'SPRING24'
            WHEN x.ordered_at BETWEEN DATE '2025-06-01' AND DATE '2025-09-01' AND MOD(x.n, 5) = 0 THEN 'SUMMER25'
            WHEN MOD(x.n, 13) = 0 THEN 'WELCOME10'
            WHEN MOD(x.n, 17) = 0 THEN 'LOYAL5' END,
       x.status, x.ordered_at,
       CASE WHEN x.status IN ('shipped', 'delivered', 'refunded')
            THEN x.ordered_at + NUMTODSINTERVAL(20 + MOD(x.n, 70), 'HOUR') END
FROM x
JOIN addresses a ON a.customer_id = x.customer_id AND a.kind = 'shipping' AND a.is_default = 1
LEFT JOIN reps r ON r.rn = MOD(x.n, r.cnt) AND MOD(x.n, 5) <> 0;

-- One to five lines an order; the product step of 17 never lands on the
-- same product twice within an order.
INSERT INTO order_lines (order_id, line_no, product_id, qty, unit_price, discount_pct)
SELECT o.order_id, l.n, p.product_id, MOD(o.order_id + l.n, 4) + 1, p.list_price,
       CASE WHEN MOD(o.order_id + l.n, 11) = 0 THEN 10 ELSE 0 END
FROM orders o
JOIN numbers l ON l.n <= MOD(o.order_id, 5) + 1
JOIN products p ON p.product_id = MOD(o.order_id * 31 + l.n * 17, 300) + 1;

BEGIN
    sales_pkg.recalculate;
END;
/

-- Open orders hold stock; top up on_hand so every reservation is covered.
MERGE INTO stock s
USING (SELECT o.warehouse_id, ol.product_id, SUM(ol.qty) AS qty
       FROM orders o JOIN order_lines ol ON ol.order_id = o.order_id
       WHERE o.status IN ('pending', 'paid', 'picking')
       GROUP BY o.warehouse_id, ol.product_id) r
ON (s.warehouse_id = r.warehouse_id AND s.product_id = r.product_id)
WHEN MATCHED THEN UPDATE SET s.reserved = r.qty, s.on_hand = s.on_hand + r.qty;

INSERT INTO invoices (invoice_id, order_id, issued_on, due_on, amount, paid_amount)
SELECT 900000 + ROW_NUMBER() OVER (ORDER BY o.order_id), o.order_id,
       TRUNC(o.ordered_at), TRUNC(o.ordered_at) + 30, o.total,
       CASE WHEN o.status IN ('shipped', 'delivered') AND MOD(o.order_id, 17) = 0
                 AND o.ordered_at >= DATE '2026-04-01' THEN 0
            WHEN o.status = 'delivered' AND MOD(o.order_id, 19) = 0
                 AND o.ordered_at >= DATE '2026-02-01' THEN ROUND(o.total / 2, 2)
            ELSE o.total END
FROM orders o
WHERE o.status NOT IN ('pending', 'cancelled');

INSERT INTO payments (invoice_id, method, amount, paid_at, card_last4)
SELECT i.invoice_id, m.method, i.paid_amount,
       CAST(i.issued_on AS TIMESTAMP(3)) + NUMTODSINTERVAL(3 + MOD(i.invoice_id, 600), 'MINUTE'),
       CASE WHEN m.method = 'card' THEN TO_CHAR(MOD(i.invoice_id * 37, 10000), 'FM0000') END
FROM invoices i
CROSS APPLY (SELECT REGEXP_SUBSTR('card,card,card,card,card,card,paypal,paypal,wire,giftcard',
                                  '[^,]+', 1, MOD(i.invoice_id, 10) + 1) AS method FROM dual) m
WHERE i.paid_amount > 0;

-- Weekday rates only (2025-01-01 was a Wednesday).
INSERT INTO exchange_rates (currency, rate_date, usd_per_unit)
SELECT c.currency, DATE '2025-01-01' + d.n - 1,
       ROUND(c.base * (1 + c.swing * SIN(d.n / 23) + 0.0001 * (MOD(d.n, 7) - 3)), 8)
FROM numbers d
CROSS JOIN (VALUES ('EUR', 1.08, 0.03), ('GBP', 1.27, 0.025), ('JPY', 0.0068, 0.05), ('SGD', 0.745, 0.015))
    c (currency, base, swing)
WHERE d.n <= DATE '2026-09-30' - DATE '2025-01-01' + 1 AND MOD(d.n + 1, 7) NOT IN (5, 6);

-- History for the movement log; the trigger that applies movements to
-- stock is created after this, so these rows do not move on_hand again.
INSERT INTO stock_movements (warehouse_id, product_id, qty, reason, order_id, moved_at)
SELECT warehouse_id, product_id, on_hand + 60, 'receipt', NULL, TIMESTAMP '2026-06-01 07:00:00'
FROM stock
UNION ALL
SELECT o.warehouse_id, ol.product_id, -ol.qty, 'sale', o.order_id, o.shipped_at
FROM orders o JOIN order_lines ol ON ol.order_id = o.order_id
WHERE o.order_id > 118000 AND o.status IN ('shipped', 'delivered')
UNION ALL
SELECT o.warehouse_id, ol.product_id, ol.qty, 'return', o.order_id, o.shipped_at + INTERVAL '9' DAY
FROM orders o JOIN order_lines ol ON ol.order_id = o.order_id
WHERE o.order_id > 110000 AND o.status = 'refunded';

INSERT INTO change_log (table_name, key_value, column_name, old_value, new_value, changed_by, changed_at)
SELECT 'ORDERS', TO_CHAR(order_id), 'STATUS', 'shipped', 'delivered', 'SVC_FULFILMENT',
       shipped_at + INTERVAL '2' DAY
FROM orders WHERE order_id > 117000 AND status = 'delivered';

INSERT INTO app_settings (setting_key, setting_value) VALUES
    ('checkout.max_lines', N'50'),
    ('checkout.tax_mode', N'by_warehouse'),
    ('feature.new_search', N'true'),
    ('inventory.restock_multiplier', N'3'),
    ('support.banner', N'Orders placed after 3 pm ship the next business day.');

INSERT INTO "Legacy Import 2019" ("Row #", "Customer Name", "Amount (USD)", "Imported?", "Notes/Comments")
SELECT n,
       CASE MOD(n, 5) WHEN 0 THEN N'ACME Corp' WHEN 1 THEN N'  padded name  ' WHEN 2 THEN NULL
                      WHEN 3 THEN N'Müller & Söhne' ELSE N'O''Hara Ltd' END,
       CASE WHEN MOD(n, 4) = 0 THEN NULL ELSE n * 123.45 END,
       CASE WHEN MOD(n, 3) = 0 THEN 'N' ELSE 'Y' END,
       CASE WHEN MOD(n, 6) = 0 THEN TO_CLOB('row failed: bad date "31/02/2019"') END
FROM numbers WHERE n <= 25;

COMMIT;

CREATE MATERIALIZED VIEW mv_daily_sales
BUILD IMMEDIATE REFRESH COMPLETE ON DEMAND AS
SELECT TRUNC(o.ordered_at) AS sales_date, o.warehouse_id,
       SUM(ol.line_total) AS revenue, SUM(ol.qty) AS units, COUNT(*) AS line_count
FROM orders o
JOIN order_lines ol ON ol.order_id = o.order_id
GROUP BY TRUNC(o.ordered_at), o.warehouse_id;

--------------------------------------------------------------- triggers
CREATE OR REPLACE TRIGGER trg_orders_status_audit
AFTER UPDATE OF status ON orders
FOR EACH ROW
WHEN (NEW.status <> OLD.status)
BEGIN
    INSERT INTO change_log (table_name, key_value, column_name, old_value, new_value)
    VALUES ('ORDERS', TO_CHAR(:NEW.order_id), 'STATUS', :OLD.status, :NEW.status);
END;
/

CREATE OR REPLACE TRIGGER trg_stock_movements_apply
AFTER INSERT ON stock_movements
FOR EACH ROW
BEGIN
    UPDATE stock SET on_hand = on_hand + :NEW.qty, updated_at = SYSTIMESTAMP
    WHERE warehouse_id = :NEW.warehouse_id AND product_id = :NEW.product_id;
END;
/

CREATE OR REPLACE TRIGGER trg_employees_salary
AFTER UPDATE OF salary ON employees
FOR EACH ROW
WHEN (NEW.salary <> OLD.salary)
BEGIN
    INSERT INTO salary_history (employee_id, effective_on, salary, reason)
    VALUES (:NEW.employee_id, TRUNC(SYSDATE), :NEW.salary, NVL(hr_pkg.g_raise_reason, 'correction'));
END;
/

CREATE OR REPLACE TRIGGER trg_customers_email
BEFORE INSERT OR UPDATE OF email ON customers
FOR EACH ROW
BEGIN
    :NEW.email := LOWER(TRIM(:NEW.email));
END;
/

CREATE OR REPLACE TRIGGER trg_app_settings_touch
BEFORE UPDATE ON app_settings
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

---------------------------------------------------------------- indexes
CREATE INDEX ix_orders_customer ON orders (customer_id, ordered_at DESC);
-- Only open orders get an entry: NULL keys are not indexed.
CREATE INDEX ix_orders_open ON orders (CASE WHEN status IN ('pending', 'paid', 'picking') THEN ordered_at END);
CREATE INDEX ix_order_lines_product ON order_lines (product_id);
CREATE INDEX ix_products_category ON products (category_id);
CREATE INDEX ix_employees_manager ON employees (manager_id);
CREATE INDEX ix_customers_last_name ON customers (UPPER(last_name), UPPER(first_name));
CREATE INDEX ix_movements_product ON stock_movements (product_id, moved_at);
CREATE UNIQUE INDEX ux_addresses_default ON addresses (
    CASE WHEN is_default = 1 THEN customer_id END, CASE WHEN is_default = 1 THEN kind END);

-- Broken on purpose: the table it reads was dropped years ago, so it stays INVALID.
CREATE OR REPLACE PROCEDURE legacy_export IS
BEGIN
    FOR r IN (SELECT * FROM legacy_orders_2019) LOOP
        NULL;
    END LOOP;
END legacy_export;
/

------------------------------- some activity, through the real packages
DECLARE
    v_id orders.order_id%TYPE;
BEGIN
    refresh_customer_tiers;
    v_id := sales_pkg.place_order(7, order_line_tab(order_line_t(12, 2), order_line_t(40, 1), order_line_t(101, 3)),
                                  1, 'WELCOME10', 11);
    sales_pkg.advance_order(v_id);
    sales_pkg.advance_order(v_id);
    sales_pkg.advance_order(v_id);
    v_id := sales_pkg.quick_order(42, 57, 2, 2);
    sales_pkg.advance_order(119990);
    sales_pkg.cancel_order(119995, 'Customer found it cheaper elsewhere');
    hr_pkg.give_raise(12, 4.5, 'merit');
    inventory_pkg.restock(3);
    report_pkg.refresh_daily_sales;
    UPDATE app_settings SET setting_value = N'4' WHERE setting_key = 'inventory.restock_multiplier';
    COMMIT;
END;
/

-- Compile anything left INVALID, then fail loudly if something other than
-- the deliberately broken legacy_export still is.
BEGIN
    DBMS_UTILITY.COMPILE_SCHEMA(USER, compile_all => FALSE);
END;
/
DECLARE
    v_bad VARCHAR2(4000);
BEGIN
    SELECT LISTAGG(object_type || ' ' || object_name, ', ') INTO v_bad
    FROM user_objects WHERE status = 'INVALID' AND object_name <> 'LEGACY_EXPORT';
    IF v_bad IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20999, 'invalid after seeding: ' || v_bad);
    END IF;
END;
/

EXIT
